services:
  konomitv:
    image: ghcr.io/tsukumijima/konomitv:latest@sha256:060676f6f9927ae3fae5c90d654f03b908c12bfcf086400c877027de4cbf25de
    restart: unless-stopped
    volumes:
      - ./config.yaml:/code/config.yaml
      - ./server/data/:/code/server/data/
      - ./server/logs/:/code/server/logs/
      - ./data/:/host-rootfs/
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - "edcb-server:${EDCB_IP}"
    ports:
      - "9999:9999"
    group_add:
      - "105" # render group
      - "44" # video group
    networks:
      - default
      - cftunnel
  tunnel:
    image: cloudflare/cloudflared@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
    restart: always
    networks:
      - cftunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
networks:
  cftunnel:
    enable_ipv6: true
