general:
  backend: "EDCB"
  always_receive_tv_from_mirakurun: false
  edcb_url: "tcp://edcb-server:4510/"
  mirakurun_url: "http://127.0.0.1:40772/"
  encoder: "QSVEncC"
  program_update_interval: 5.0
  debug: true
  debug_encoder: false
server:
  port: 9999
  custom_https_certificate: "/server.crt"
  custom_https_private_key: "/server.key"
tv:
  preferred_terrestrial_region: null
  max_alive_time: 10
  debug_mode_ts_path: null
video:
  recorded_folders: ["/record"]
  exclude_scan_paths: []
capture:
  upload_folders: ["/capture"]
